- pygraphviz/agraph.py
- pygraphviz/tests/test_edge_attributes.py
- pygraphviz/tests/test_graph.py
- pygraphviz/tests/test_node_attributes.py
This PR allows update of node and edge attributes when you call add_node() and add_edge().
Addresses #15
> Attr update

- .gitignore
- pygraphviz/agraph.py
- pygraphviz/tests/test_clear.py
I found one more case related clear function #65  and implemented both unit test to crash pygraphviz and fix to avoid it.
> One more case related AGraph.clear

- .travis.yml
wheels can be auto-uploaded to pypi, would be a big help for me (https://docs.travis-ci.com/user/deployment/pypi/)
> add wheel builds

- pygraphviz/agraph.py
> Wait for subprocess to prevent ResourceWarning

- pygraphviz/graphviz_wrap.c
Fixes https://github.com/pygraphviz/pygraphviz/issues/177
> Fix graphviz_wrap.c _wrap_agwrite for Pypy3

- .travis.yml
Fixes #231
based on discussion [here](https://github.com/tqdm/tqdm/issues/460)
> Fix osx testing so it works... even tho it fails

- .github/workflows/deploy-docs.yml
Build and deploy docs to `latest` in the pygraphviz/documentation repo on PR merge in pygraphviz/pygraphviz.
> Add workflow for doc deploy.

- .github/workflows/deploy-docs.yml
Add `git --config` options for name and email to properly attribute deploy commits.
> Modify doc deploy config name/email.

- .github/workflows/deploy-docs.yml
Followup to fix mis-named config options in #276
> Fix config names

- doc/source/tutorial.rst
A minor doc change to verify that the doc deploy workflow for `latest` is working as expected.
To be merged after #274
> TEST: Minor doc change to test doc deploy workflow.

- .coveragerc
- .gitignore
- pygraphviz/tests/test_graph.py
Primarily focused on improving the coverage of the `agraph` module.
> TST: Add/modify tests to improve coverage

- pygraphviz/agraph.py
> Raise error for tred and acyclic on undirected graph

- pygraphviz/agraph.py
- pygraphviz/tests/test_graph.py
> fix directed nature of AGraph.copy()

- .circleci/config.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
- INSTALL.txt
- setup.py
> Drop Py 3.7

- .circleci/config.yml
- .github/workflows/conda-macos.yml
- .github/workflows/conda-ubuntu.yml
- .github/workflows/conda-windows.yml
- .github/workflows/conda.yml
- INSTALL.txt
- doc/source/conf.py
Add a GitHub workflow to test installing `pygraphviz` with `conda` via the conda-forge channel.
> CI: Add workflow to test install via conda-forge.

- .gitignore
- CONTRIBUTING.rst
Closes #378.  I ran through these steps on my system, and it seemed to work.  Not the most thorough way to validate, but it's something.
I pretty much just made a straight edit of the networkx doc, since I assume you all would rather keep most of those conventions consistent.
Some sections from that doc, I don't know enough to tell whether they are applicable (e.g. Review Process, Guidelines, Policies), so I made my best guesses, and removed or kept them accordingly.
Not sure if the need for a C/C++ compiler should be mentioned?
Hope it helps!
> Add contrib doc

- pygraphviz/agraph.py
- pygraphviz/tests/test_layout.py
Related to #205 . 
Adds `osage` and `patchwork` to the list of graphviz commands per this list: https://graphviz.org/docs/layouts/
> Add osage and patchwork to progs list

- requirements/doc.txt
> Update doc dependencies

- .circleci/config.yml
- .github/workflows/circleci.yml
- .github/workflows/deploy-docs.yml
- doc/Makefile
We stopped doing it for NetworkX and other projects.
> Stop building pdf of the docs

- .github/workflows/test.yml
- INSTALL.txt
> Update tests for macOS Sonoma v14

- requirements/doc.txt
> Update doc requirements

- .github/workflows/test.yml
- INSTALL.txt
See https://github.com/pygraphviz/pygraphviz/issues/490#issuecomment-1889921017
> Remove unnecessary pip flags

- doc/source/conf.py
Fixes #541
together with https://github.com/sphinx-gallery/sphinx-gallery/pull/1385
> Avoid adding benchmark results to docs
