pygraphviz/pygraphviz

pygraphviz/graphviz.i

in swig-3* a line starting with '#' raises a
Error: Unknown SWIG preprocessor directive
Exchanging the comment marker solves this.
Signed-off-by: Justin Lecher <jlec@gentoo.org>

Convert line comment marker for latest swig

---

setup_commands.py

If the graphviz libraries and headers are installed directly into
system-wide default directories, pkg-config does not produce any -L or -I
flags, since they are not needed.

Fixed #71: Added support for empty library and include dirs in setup.

---

pygraphviz/agraph.py

Otherwise, it crashes with "TypeError: can't use a string pattern on a
bytes-like object" when the errors list is not empty.

The warnings module expects a string, not bytes.

---

.travis.yml
pygraphviz/tests/test_setup.py
setup.py
setup_extra.py

- implemented search for graphviz installation using dpkg
- improve handling of empty strings, now if path not found error message is generated
- added unit tests to cover new functionality
- this pull request addresses installation issues for Ubuntu (reported in #72  and #71 )

Auto detect graphviz installation path on ubuntu

---

setup_extra.py

And where dpkg is not avalaible at all.
This is the case on arch linux
Currently installing latest RC version with pip (2 or 3) fails on arch linux:
```
Running setup.py install for pygraphviz ... error
Complete output from command /usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-SnmpOq/pygraphviz/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-ZtKgcM-record/install-record.txt --single-version-externally-managed --compile:
running install
Trying dpkg
dpkg-query: no path found matching pattern *graphviz*
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/tmp/pip-build-SnmpOq/pygraphviz/setup.py", line 93, in <module> …
```

Fix build when libcgraph headers are accessible without additional include path

---

pygraphviz/agraph.py

Unflatten is built-in graphiz tool for reduction of the aspect ratio of graphiz layout [documentation](http://www.graphviz.org/pdf/unflatten.1.pdf).
This PR implements unflatten support for Agraph in 13 lines of code, reusing existing helper functions.

Add support for unflatten

---

pygraphviz/agraph.py

I noticed that I was getting the following deprecation warnings when running pygraphviz under python 3.7.2:
```
pygraphviz/agraph.py:20: DeprecationWarning: Using or importing the ABCs from
'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will
stop working
```
```
pygraphviz/agraph.py:144: DeprecationWarning: invalid escape sequence \s
```
This PR fixes those warnings.

Fix deprecation warnings

---

doc/source/conf.py

This is necessary to build the docs with sphinx-2.x.
sphinx-2.0 removed the deprecated function.
See https://bugs.python.org/issue34967 for similar changes in cpython.

doc: use add_object_type() instead of deprecated add_description_unit()

---

pygraphviz/agraph.py
pygraphviz/tests/test_readwrite.py

Hi there! Thanks a ton for this Python binding.
This PR adds support for passing Path-like objects through much of the PyGraphviz API.
`pathlib.Path` (Python 3.4+) and other `Path`-like objects respond to `open`, so this PR tests for them based on that attribute.
Please let me know if there's anything else I can do!

agraph: Allow _get_fh to accept a Path-like object

---

pygraphviz/agraph.py
pygraphviz/tests/test_close.py

Browse code while investigating [\[SO\]: Pygraphviz crashes after drawing 170 graphs (@CristiFati's answer)](https://stackoverflow.com/questions/60876623/pygraphviz-crashes-after-drawing-170-graphs/61050313#61050313).
Although closing the handle doesn't have any visible effect, it's better to happen automatically when an object is destroyed (instead at `with` end). Also calling *close* twice (as it's public) would no longer crash.
As a side note, many tests failed when I ran them (original code).
**Recap** - this patch fixes:
- The double *close* crash
- Handle close performed at object destruction instead of the context manager's
- Better organize the code
- The 3<sup>rd</sup> commit excludes inherited handles from being closed (as it's each entity's responsibility to release resources …

AGraph Graphviz handle close mechanism

---

setup_extra.py

Adding an additional include path to find `graphviz/cgraph.h`. For example, running 
```
pkg-config --cflags-only-I libcgraph
```
with MacPorts returns
```
-I/opt/local/include/graphviz
```
(and similarly for Homebrew, except for `usr` instead of `opt`)

Add additional include path

---

doc/source/reference/faq.rst

The old tickets are the first indication that it is hard to install on
Windows. I put a link to more recent Issues on Github as a replacement.

Update the links in the faq .rst file.

---

INSTALL.txt
requirements/test.txt
setup.py

Since pygraphviz no longer supports Python 2 and entirely relies
on built-in unittest.mock module, the dependency on mock is no longer
necessary.

Remove stale mock dependency

---

INSTALL.txt
pygraphviz/agraph.py
requirements/test.txt
setup.cfg
setup.py

Since pygraphviz no longer supports Python 2, the unicode strings
in doctests are no longer meaningful.  Update the tests to use plain
Python 3 str, and remove doctest-ignore-unicode hack.
// This conflicts a bit with my other PR, I can rebase if that one is merged.

Update doctests for Python 3, remove doctest-ignore-unicode

---

pygraphviz/agraph.py

Take out code for str (Py3) vs unicode (Py2).

remove py2 stuff from agraph.py

---

pygraphviz/agraph.py
pygraphviz/tests/test_graph.py

The equals function was based on dot string format which changes (adds and remove spaces, etc) by operating system, version of graphviz, etc. That makes testing quite hard. It can also lead to strange results where changing a graph and then changing it back leads to not equal. 
This new ```__eq__``` and ```copy``` use the nodes and attributes in the object to check for equality and to copy.
The state of the object is no longer designated by the dot file produced.

Update __eq__() and copy() to use the stored nodes and edges

---

.github/workflows/test.yml
pygraphviz/agraph.py
pygraphviz/tests/test_layout.py

This adds CI testing for Windows using the official Graphviz 64bit cmake installer.  There is also an official MSBuild build, but it doesn't include header files.  We should also look into the chocolatey packages (I am not sure if they include header files):
https://chocolatey.org/packages/Graphviz/2.44.1
There are a couple of issues with the official Graphviz 64bit cmake installer / GH action:
1. The cmake installer is new and does not install everything (e.g., neato, gvpr, and fdp are missing).  This is a known issue and it is being worked on.  You can find more information here:
https://gitlab.com/graphviz/graphviz/-/issues/1753
2. I set the environment variable ``PY_IGNORE_IMPORTMISMATCH=1`` to avoid getting this ImportMismatchError:
```
E   _pytest.pathlib.ImportPathMismatchError: …
```

Test on Windows

---

pygraphviz/agraph.py

Removes a one-liner in favor of the more standard `isinstance(obj, str)` call. The `is_string_like` function is technically in the public namespace, so maybe this would require a deprecation (not sure what the policy is there) but since it was such a small tangential change I figured I'd try the simple removal first.
If a deprecation is preferred LMK!

MAINT: rm one-line is_string_like function.

---

pygraphviz/agraph.py

`AGraph` has a method called `prepare_nbunch` which, according to the comments in the code, is only intended for internal use. I propose prepending `_` to the method to indicate that it is intended to be a private, internal method.
This change has the potential to break user code. I wasn't sure what to do re: deprecating vs. just making the change. If a deprecation is preferred, LMK and I'll update the PR with a deprecation warning instead.
Finally, there was one place where existing code could be replaced with the `prepare_nbunch` method, see caac7f4

MAINT: Make prepare nbunch private

---

pygraphviz/agraph.py
pygraphviz/tests/test_graph.py

To include default attribute values in equals dunder, I added a new method `ItemAttribute.to_dict()` that differs from `ItemAttribute.iteritems()`. The `iteritems` ignores attributes if the value equals the default. The `to_dict` includes the attribute whether it has the default value or not.
Fixes #284

Fix equals dunder to consider attributes.

---

.github/workflows/test.yml

Test the 2.46 release installer.  It looks like the release got temporarily delayed from being announced due to a minor CI issue:
https://gitlab.com/graphviz/graphviz.gitlab.io/-/merge_requests/248/diffs
Once the announcement is official, we need to double-check that this is still the right installer and then merge.

Use graphviz-2.46.0 for window's tests

---

INSTALL.txt
doc/source/reference/news.rst

@rossbar I am thinking of merging this as is (i.e., with the ``--pre`` flag included).  I would like to wait and see if chocolatey updates pygraphviz soon: https://github.com/chocolatey-community/chocolatey-coreteampackages/issues/1609
Before releasing 1.7, we would update the INSTALL page and hopefully add instructions for using ``choco`` to install Graphviz 2.46.0.  In the meantime, anyone using these instructions will get ``pygraphviz-1.7rc2``.

Update 1.7 docs

---

.github/workflows/test.yml

The CI jobs for testing on fedora are failing due to failed checks of gpg-keys in the installation process. The failed key checks aren't specific to graphviz, so the failures seem unrelated. This PR works around this issue by skipping the key checks with the `--nogpg` flag. I'm not too familiar with `dnf`, so there may be a better way to do this.

CI: fix failing fedora jobs.

---

README.rst

The installation details are not found in INSTALL.rst (because that file does not exist). Changed reference to INSTALL.txt.

Fixed installation readme path in homepage readme.

---

pygraphviz/agraph.py

Saw this in the docs a couple of times. So here is a PR in case it is of use.

docstring typos (paris -> pairs)

---

.github/workflows/conda-macos.yml
.github/workflows/conda-ubuntu.yml
.github/workflows/conda-windows.yml

Once on `main`, should enable re-running the conda-forge workflows via button-press in the GitHub UI

Add workflow_dispatch to enable manual triggering of conda workflows.

---

.github/workflows/conda-macos.yml
.github/workflows/conda-ubuntu.yml
.github/workflows/conda-windows.yml

Some conda versions < 4.11 fail to parse the Python version `3.10` correctly, see e.g. conda/conda#10969
This updates the conda-forge test workflows by:
1. Updating conda prior to environment creation
2. Being explicit about which Python version to use in the conda env

Update conda, use explicit Python version in CI.

---

setup.py

Faced issues building pygraphviz with Graphviz 3+, since specifying `/DGVDLL` is now mandatory.
```
>>> define_macros = []
>>> define_macros = define_macros.append(("GVDLL", None))
>>> print(define_macros)
None
```
Closes #408

Ensure define_macros remains a list on Windows

---

pygraphviz/graphviz_wrap.c
pygraphviz/tests/test_readwrite.py

Resolves https://github.com/pygraphviz/pygraphviz/issues/213

Fix FILE* resource leak in agread() wrapper 

---

.github/workflows/test.yml
setup.py

The 3.11.0 candidate 1 was released Monday, 2022-08-08. We've been testing against 3.11-dev for sometime and haven't seen any issues.
3.11.0 final is expected to be released on Monday, 2022-10-03. If we run into any 3.11 issues, we can address them and make a 1.10.1 release.

Announce support for Python 3.11

---

pygraphviz/agraph.py
pygraphviz/graphviz.i
pygraphviz/graphviz.py
pygraphviz/graphviz_wrap.c

See [the discussion in 415](https://github.com/pygraphviz/pygraphviz/pull/415#issuecomment-1210458418).
The simple attempt results in `dup` being added to more wrapped functions, which causes an infinite hang in the `pygraphviz/tests/test_drawing.py::test_drawing_no_error_with_no_layout`, at least locally.

Move modifications for proper file closing from generated `graphviz_wrap.c` to swig file

---

pygraphviz/agraph.py
pygraphviz/tests/test_graph.py

Fixes the carry over of the `name` and `strict` attributes when copying. Fixes #426 .

Fix passthrough of graph attributes when copying

---

INSTALL.txt

It seems `brew` no longer reliably installs graphviz on the default paths where the header files can be discovered. This is likely dependent on the version of macos, brew, and perhaps graphviz.
Updates the install instructions with brew-specific instructions for specifying include and library dirs manually.
Closes #443, insofar as it's possible to "close" the continual installation issues :)

Add a note for brew install instructions.

---

INSTALL.txt

Since pip 23.1 the`--global-option` and `--build-option` flags are being deprecated in favour of `config-settings`, more details at https://pip.pypa.io/en/stable/news/#v23-1.
This change aims to update the install instructions to work with pip versions from 23.1 and graphviz install via brew
Should resolve issue #454

Update install instructions for usage with brew

---

.github/workflows/circleci.yml

Fixes issues in CI with circleci doc artifact link. Followed the procedure described in larsoner/circleci-artifacts-redirector-action#40.

CI: Add circleci artifact redirector token.

---

INSTALL.txt

Following a pip version update, the `--config-settings` feature will no longer be supported by default. As a result, an error message will be displayed suggesting alternative usage:
> DEPRECATION: Config settings are ignored for project pygraphviz from https://files.pythonhosted.org/packages/ee/7e/7366c082f959db7ee18a16fc38dc594158ede65ca789bef87751ed5130c7/pygraphviz-1.10.zip. pip 23.3 will enforce this behaviour change. A possible replacement is to use --use-pep517 or add a pyproject.toml file to the project.
In response, this pr adds an option `--use-pep517` that is documented within the installation instructions.
<details><summary>Screenshots</summary>
<h6>Before adding <code>--use-pep517</code></h6>
<h6>After adding <code>--use-pep517</code></h6>
</details>

Add pep517 flag for config-settings

---

pygraphviz/agraph.py
pygraphviz/tests/test_graph.py

Fix #472 
Some attributes are not copied when copying a graph, like edges keys. This fix copies edge keys to the target graph so it matches the original graph.

Copy edges keys when copying a graph

---

.github/workflows/test.yml
INSTALL.txt

Fixed the manual installation instructions for Windows. I tried to copy-paste into my terminal but produced some errors. I believe there were some extra ".
I skipped the contributing guidelines because this change does not affect funcionality and I won't be working on this project in the near future.
Thanks in advance, I hope this helps :)

Windows Manual Installation Fix

---

pygraphviz/agraph.py
pygraphviz/tests/test_graph.py

Fixes #519 
IIUC `__init__` already uses `handle=None` as an [indicator that something may have gone wrong during initialization](https://github.com/pygraphviz/pygraphviz/blob/fce4667903d56f4cd0d4f5e7770b238f211d5481/pygraphviz/agraph.py#L118). This PR leverages this fact to avoid calling the low-level `gv.agnameof` on `self.handle` when `self.handle is None`.
@aaronzo the test and proposed fix are basically ripped right out of your suggestions in #519 so I went ahead and added you as a co-author - hopefully that's okay! Should any other corner-cases be added to the test suite to ensure this fix covers the full gamut?

Fix segfault from repr attempting to access attrs on uninitialized instance

---

pygraphviz/agraph.py

Hi pygraphviz team,
Thanks for this great project!
I'm using `pygraphviz` through [`networkx`](https://github.com/networkx/networkx) for some python widgets that are added to a host application in the form of a plugin.
In Windows OS, running [`networkx.drawing.pygraphviz_layout`](https://github.com/networkx/networkx/blob/3c0f096f66ab352cfaf8dbe2d5fc5731cbbc4338/networkx/drawing/nx_agraph.py#L261C5-L261C22) leads to a terminal window appearing and disappearing very quickly. This seems to happen exactly during execution of [`pygraphviz.agraph.AGraph._run_prog`](https://github.com/pygraphviz/pygraphviz/blob/fce4667903d56f4cd0d4f5e7770b238f211d5481/pygraphviz/agraph.py#L1381-L1388) on the subprocess call:
https://github.com/pygraphviz/pygraphviz/blob/fce4667903d56f4cd0d4f5e7770b238f211d5481/py …

Avoid subprocess window creation with agraph.AGraph._run_prog

---

.circleci/config.yml
.github/workflows/conda-macos.yml
.github/workflows/conda-ubuntu.yml
.github/workflows/conda-windows.yml
.github/workflows/coverage.yml
.github/workflows/deploy-docs.yml
.github/workflows/lint.yml
.github/workflows/test.yml
INSTALL.txt
pyproject.toml

PyPy is still working on 3.11 support (3.12 and 3.13 support hasn't started yet):
https://github.com/pypy/pypy/milestone/15

Drop support for Python 3.10 (SPEC 0)

---

INSTALL.txt

We shouldn't put pip as an explicit recommendation if we need people to use custom pip config for Windows and MacOS. This doesn't recommend conda either, just removes the explicit recommendation.

DOC: remove pip install as recommendation

---

.github/workflows/test.yml

Update fedora tests

---

pygraphviz/graphviz.i
pygraphviz/graphviz.py
pygraphviz/graphviz_wrap.c

A few minor commits, then the focus of this series in the final one whose commit message I quote below.
----
This code was over-allocating and then adjusting string content to truncate the copied string. This has a couple of minor weaknesses:
1. One more byte than necessary is allocated, increasing heap pressure.
2. Memory safety tools like Address Sanitizer cannot spot 1-byte overruns.
(1) is not significant, but (2) can make it harder to debug memory safety problems. This change tightens the bounds:
```
┌───┬───┬───┬───┬───┬───┐
original val:            │ < │ f │ o │ o │ > │000│
└───┴───┴───┴───┴───┴───┘
┌───┬───┬───┬───┬───┐
copy before this change:     │ f │ o │ o │000│000│
└───┴───┴───┴───┴───┘
┌───┬───┬───┬───┐ ▲
copy after this change:      │ f │ o │ o │000│ │
└───┴───┴───┴───┘ │
│ …
```

More precise allocation for string copy in SWIG glue
